---
name: threads-lite
version: 0.020_001
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Yet another threads library
license: perl
configure_requires:
  Module::Build: 0
requires:
  Storable: 2.05
  perl: 5.01
build_requires:
  Module::Build: 0
  Test::More: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  threads::lite:
    file: lib/threads/lite.pm
    version: 0.020_001
  threads::lite::list:
    file: lib/threads/lite/list.pm
    version: 0
  threads::lite::tid:
    file: lib/threads/lite/tid.pm
    version: 0
resources:
  license: http://dev.perl.org/licenses/
