---
abstract: 'Actor model threading for Perl'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  Time::HiRes: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
keywords:
  - threads
  - channels
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: threads-lite
provides:
  threads::lite:
    file: lib/threads/lite.pm
    version: 0.033
  threads::lite::list:
    file: lib/threads/lite/list.pm
    version: 0.033
  threads::lite::queue:
    file: lib/threads/lite/queue.pm
    version: 0.033
  threads::lite::tid:
    file: lib/threads/lite/tid.pm
    version: 0.033
requires:
  Exporter: 5.57
  Storable: 2.05
  experimental: 0.003
  perl: 5.010001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=threads-lite
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/threads-lite/tree
version: 0.033
