---
name: threads-lite
version: 0.027
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Erlang style threading library
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=threads-lite
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/threads-lite/tree
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
requires:
  Exporter: 5.57
  Storable: 2.05
  perl: 5.01
configure_requires:
  Module::Build: 0
provides:
  threads::lite:
    file: lib/threads/lite.pm
    version: 0.027
  threads::lite::list:
    file: lib/threads/lite/list.pm
    version: 0.025
  threads::lite::queue:
    file: lib/threads/lite/queue.pm
    version: 0.025
  threads::lite::tid:
    file: lib/threads/lite/tid.pm
    version: 0.025
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - threads
  - channels
